# WhorAizen shaders.properties
pack.name=WhorAizen
pack.description=A cinematic, bright, and moody shader pack.

# Profile definitions
profile.Potato=
profile.Low=
profile.Medium=
profile.High=
profile.Ultra=

# Buffer formats
colortex0Format=RGBA16F
colortex1Format=RGBA8
colortex2Format=RGBA16F
colortex3Format=RGBA8
colortex4Format=RGBA16F
colortex5Format=RGBA16F

# Set default profile
profile=Medium
