# WhorAizen shaders.properties
pack.name=WhorAizen
pack.description=A cinematic, bright, and moody shader pack.

# Profile definitions
profile.Potato=
profile.Low=
profile.Medium=
profile.High=
profile.Ultra=

# Set default profile
profile=Medium
